---
name: "Build dev images"
on:
  workflow_dispatch:

jobs:
  docker:
    name: Docker Image Build
    runs-on: ubuntu-latest
    needs: [pypi]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta for TAG
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKER_IMAGE }}
          tags: |
            type=raw,value=dev

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  docker_in_docker:
    name: Docker Image Build with Docker support
    runs-on: ubuntu-latest
    needs: [pypi]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta for TAG
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKER_IMAGE }}
          tags: |
            type=raw,value=dev-dind

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.docker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}