---
name: "Testing & Docker Build for edge"

on:
  push:
    branches:
      - main

jobs:
  pytest:
    name: Run Pytest Validation
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10']
      max-parallel: 3
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          echo "PY_COLORS=1" >> $GITHUB_ENV
          echo "ANSIBLE_FORCE_COLOR=1" >> $GITHUB_ENV
          pip install pytest pytest-cov pytest-html pytest-dependency pytest-metadata
          pip install -r requirements.txt
      - name: Run Pytest
        env:
          ARISTA_TOKEN: ${{ secrets.ARISTA_TOKEN }}
        run: |
          echo "PY_COLORS=1" >> $GITHUB_ENV
          echo "ANSIBLE_FORCE_COLOR=1" >> $GITHUB_ENV
          python setup.py develop
          make test
      - uses: actions/upload-artifact@v3
        with:
          name: pytest-reporting
          path: |
            report.html
            tests/htmlcov/**


  docker:
    name: Docker Image Build
    runs-on: ubuntu-latest
    needs: [pytest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta for TAG
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKER_IMAGE }}
          tags: |
            type=edge,enable=true,priority=700

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}